language: python

sudo: false

env:
    - TOXENV=py36

install:
    - travis_retry pip install tox

script:
    # set the TOXENV to the python environment selected by the travis agent
    - export TOXENV="$(if [ "${TRAVIS_PYTHON_VERSION}" == "pypy" ]; then echo "pypy"; else echo py${TRAVIS_PYTHON_VERSION/\./}; fi)"
    - travis_retry tox
