language: python
sudo: false

env:
    - TOXENV=py36

python:
- 3.6
install:
- travis_retry pip install tox
script:
- travis_retry tox
deploy:
  provider: pypi
  user: Alex.F
  password:
    secure: cvGEYU7qF/IbhlMwRry8yhYSNZG7harvMuAJLtX9sqn6lSPqipzMPrNUjrUxL2DSgqu5MiNWOggLSlHH7UoaaEh5mD7h0JmijceACZ714yV1lL6Bavuj58uvQdZPOUwnfTJHIiR7fzdH4+LdgM02TJ5flK9v8je64XO7RTJy5hktm6VUdusqYkCMiSyks4y0qdotvqG6zcJNsIu8uZshV92IM90ABLUTLjx3onyF8qLBlhAmOOOTLu0xBydmFxm2t46Hmjkzw8r8shZYJhqzIXFizX8x3egWU6ziu8xSK0NHk5Gv9hLkRKHOOL4eoVkXzCkPp2rgUv0Jj/hQXF73MfsHWdBJkjDoJ+aj7Av/ZcLKeADHjif+cpzikA6Uzilp/uTNv3aJfLSKbEXAwffTbdC1aLGyoq/VVLYLsfHeFR02MlqnFTw7Xkh4bKLKc6YnIZXgRvKZvv/QnoW6SNgW7diejZFgP/3jSEm5fyj0Zavo8oLo1ixjzytjdDH11p/8bjur1cvpWL1CnxjD1FTkG2Mm+lr/K7YkLkXcxh9MMVIuaMXRzuVJ+GL3EER6HiXmk+uJ+MaEqhFoZvaPisbTTntL30lO9t+OTtQHn7NjBtgZjNSf5EswNlIxXDNbCo6qULrAI4CF0bIkg8iyI3j0vIhvWLRe330L3KPi7m6gY8k=
  on:
    distributions: sdist bdist_wheel
    repo: gfreezy/slacker-asyncio
